/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import interface_windows_ciai.Interface_windows_CIAI;
import java.io.IOException;

/**
 *
 * @author michael
 */
public class Parametrage extends javax.swing.JFrame {

    Interface_windows_CIAI app;
    
    /**
     * Creates new form Parametrage
     */
    public Parametrage(Interface_windows_CIAI inter) {
        app = inter;
        setLocationByPlatform(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        B_envoi_parametrage = new javax.swing.JButton();
        j_nb_palette_A = new javax.swing.JTextField();
        j_nb_palette_B = new javax.swing.JTextField();
        j_nb_pourcentage = new javax.swing.JTextField();
        B_annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closing(evt);
            }
        });

        jLabel1.setText("Interface de paramétrage du lot de fabrication");

        jLabel2.setText("Nombre de palettes A");

        jLabel3.setText("Nombre de palettes B");

        jLabel4.setText("% d'erreurs autorisées par carton");

        B_envoi_parametrage.setText("Confirmer");
        B_envoi_parametrage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_envoi_parametrageActionPerformed(evt);
            }
        });

        j_nb_palette_A.setText("42");

        j_nb_palette_B.setText("42");

        j_nb_pourcentage.setText("50");

        B_annuler.setText("Annuler");
        B_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j_nb_palette_A)
                            .addComponent(j_nb_palette_B)
                            .addComponent(j_nb_pourcentage))))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(B_annuler)
                .addGap(51, 51, 51)
                .addComponent(B_envoi_parametrage)
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(j_nb_palette_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(j_nb_palette_B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(j_nb_pourcentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_envoi_parametrage)
                    .addComponent(B_annuler))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_envoi_parametrageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_envoi_parametrageActionPerformed
        // TODO add your handling code here:
        /*A modifier*/
        int nb_palette_commande_A = -1;
        int nb_palette_commande_B = -1;
        int pourcentage = -1;
        try {
            nb_palette_commande_A = Integer.parseInt(j_nb_palette_A.getText());
            nb_palette_commande_B = Integer.parseInt(j_nb_palette_B.getText());
            pourcentage = Integer.parseInt(j_nb_pourcentage.getText());
            if (nb_palette_commande_A < 0 || nb_palette_commande_B < 0 || pourcentage < 0)
            {
                app.error("Données invalides", "Entrez des valeurs positives pour les différentes paramètres.");
            }
            else
            { /* censé veréifier si la commande est possible ici ? C'est passé ou ?*/
                try {
                    String parametrage_lot = "0 " + nb_palette_commande_A + " " + nb_palette_commande_B + " " +  pourcentage;
                    app.network.send_message(parametrage_lot);
                    this.dispose();
                } catch (IOException ex) {
                    app.error("IO Exception", "Could not send the command to the host!");
                    //ex.printStackTrace(System.err);
                }    
                //ouverture de la fenêtre de suivi
                Suivi fv = new Suivi(app);
                fv.setVisible(true);
                this.dispose();
            }
        } catch (java.lang.NumberFormatException ex){
            //System.out.println("Rentrez les bonnes valeurs pour les différentes paramètres.");
            app.error("Format numérique", "Entrez des valeurs valides pour les différentes paramètres.", ex);
        }
        
    }//GEN-LAST:event_B_envoi_parametrageActionPerformed

    private void B_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_annulerActionPerformed
        dispose();
        app.quit();
    }//GEN-LAST:event_B_annulerActionPerformed

    private void closing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closing
        dispose();
        app.quit();
    }//GEN-LAST:event_closing

    
    /*public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Parametrage().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_annuler;
    private javax.swing.JButton B_envoi_parametrage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField j_nb_palette_A;
    private javax.swing.JTextField j_nb_palette_B;
    private javax.swing.JTextField j_nb_pourcentage;
    // End of variables declaration//GEN-END:variables
}
